language: php

php:
  - 7.1
  - 7.2

before_install:
  # turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Nette/Tester
  - composer run-script tester

jobs:
  include:
    - env: title="Lowest Dependencies 7.1"
      php: 7.1
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - composer run-script tester

    - env: title="Lowest Dependencies 7.2"
      php: 7.2
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - composer run-script tester

    - stage: Quality Assurance
      php: 7.2
      script:
        - composer run-script qa

    - stage: Test Coverage
      php: 7.2
      script:
        - composer run-script coverage
      after_script:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
        - php php-coveralls.phar --verbose --config tests/.coveralls.yml

    - stage: Phpstan
      php: 7.2
      script:
        - composer run-script phpstan-install
        - composer run-script phpstan

  allow_failures:
    - stage: Test Coverage

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
