name: "Nette Tester"

on:
  pull_request:
  workflow_dispatch:

  push:
    branches: [ "*" ]

  schedule:
    - cron: "0 8 * * 1"

jobs:
  test85:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.5"

  test84:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.4"

  test83:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.3"

  test82:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.2"

  test81:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.1"

  testlower:
    name: "Nette Tester"
    uses: contributte/.github/.github/workflows/nette-tester.yml@master
    with:
      php: "8.1"
      composer: "composer update --no-interaction --no-progress --prefer-dist --prefer-stable --prefer-lowest"
